# Generated by Django 2.0.1 on 2018-01-24 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/avatar.png', null=True, upload_to='avatars/', verbose_name='avatar para tu perfil'),
        ),
    ]
