# Generated by Django 2.0.1 on 2018-01-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20180104_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Cumplido', 'Cumplido'), ('Vencido', 'Vencido')], default='Activo', max_length=100),
        ),
    ]
