# Generated by Django 2.0.1 on 2018-01-04 20:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_auto_20180104_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
