# Generated by Django 2.0.1 on 2018-02-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('meeting', '0001_initial'),
        ('tasks', '0005_auto_20180106_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='name_meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', related_name='tasks', to='meeting.Meeting'),
        ),
        migrations.AddField(
            model_name='task',
            name='name_project',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', related_name='tasks', to='project.Project'),
        ),
    ]
