# Generated by Django 2.0.1 on 2018-02-13 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20180212_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='name_meeting',
            new_name='meeting',
        ),
    ]
