# Generated by Django 2.0.1 on 2018-02-13 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20180213_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='meeting',
            new_name='name_meeting',
        ),
    ]
