# Generated by Django 2.0.1 on 2018-02-13 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20180213_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='name_meeting',
            new_name='meeting',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='name_project',
            new_name='project',
        ),
    ]
