# Generated by Django 2.0.1 on 2018-02-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_auto_20180213_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='expiry',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='starts',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
