# Generated by Django 2.0.1 on 2018-03-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_auto_20180313_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('Alta', 'Q3'), ('Media', 'Q2'), ('Baja', 'Q1')], max_length=100),
        ),
    ]
