# Generated by Django 2.0.1 on 2018-04-24 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_auto_20180424_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='name',
            new_name='title',
        ),
    ]
