# Generated by Django 2.0.1 on 2018-03-13 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20180313_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to='meeting.Meeting'),
        ),
    ]
