# Generated by Django 2.0.1 on 2018-05-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_fastnote'),
        ('project', '0006_auto_20180326_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='participants',
            field=models.ManyToManyField(blank=True, to='accounts.Profile'),
        ),
    ]
