# Generated by Django 2.0.1 on 2018-02-27 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='name',
            new_name='name_file',
        ),
    ]
