# Generated by Django 2.0.1 on 2018-02-28 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180228_1754'),
        ('meeting', '0005_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note', to='accounts.Profile')),
                ('meeting', models.ForeignKey(on_delete='CASCADE', related_name='note', to='meeting.Meeting')),
            ],
        ),
    ]
