# Generated by Django 2.0.1 on 2018-03-05 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0006_note'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Action',
            new_name='Order',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='name_action',
            new_name='name_order',
        ),
    ]
