# Generated by Django 2.0.1 on 2018-03-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0007_auto_20180305_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=320)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('meeting', models.ForeignKey(on_delete='CASADE', related_name='action', to='meeting.Meeting')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', related_name='order', to='meeting.Meeting'),
        ),
    ]
