# Generated by Django 2.0.1 on 2018-03-13 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0012_auto_20180313_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='user',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to=settings.AUTH_USER_MODEL),
        ),
    ]
