# Generated by Django 2.0.1 on 2018-03-23 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0013_auto_20180313_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='note',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='meeting.Meeting'),
        ),
    ]
