# Generated by Django 2.0.1 on 2018-03-23 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0014_auto_20180323_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='meeting.Meeting'),
        ),
    ]
